project_id = "dycrfntiziwkltcdtxmu"

[functions.chat]
verify_jwt = false

[functions.twilio-whatsapp]
verify_jwt = false

[functions.twilio-sms]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false
